(function($){
'use strict';
function showToast(message,type){var palette={success:'linear-gradient(135deg,#496f5d,#6d9b7f)',info:'linear-gradient(135deg,#704b45,#b88955)',error:'linear-gradient(135deg,#9a4d48,#c96a61)'};Toastify({text:message,duration:2800,close:true,gravity:'top',position:'right',stopOnFocus:true,style:{background:palette[type||'info'],borderRadius:'12px'}}).showToast();}
window.showLuminaToast=showToast;
function getCart(){try{return JSON.parse(localStorage.getItem('luminaCart')||'[]')}catch(e){return[]}}
function setCart(cart){localStorage.setItem('luminaCart',JSON.stringify(cart));updateCartBadge();}
function updateCartBadge(){var count=getCart().reduce(function(s,x){return s+(x.qty||1)},0);$('.js-cart-count').text(count);}
$(function(){
$('.js-year').text(new Date().getFullYear()); updateCartBadge();
$('.js-add-cart').on('click',function(){var btn=$(this),item={id:btn.data('id'),name:btn.data('name'),price:Number(btn.data('price')),image:btn.data('image'),qty:1},cart=getCart(),found=cart.find(function(x){return x.id===item.id});if(found){found.qty+=1}else{cart.push(item)}setCart(cart);showToast(item.name+' added to your bag.','success');});
$('.js-newsletter').on('submit',function(e){e.preventDefault();if(this.checkValidity()){showToast('Welcome to the LUMINA list.','success');this.reset()}else{$(this).addClass('was-validated')}});
$('.js-validate').on('submit',function(e){e.preventDefault();var form=this;if(!form.checkValidity()){$(form).addClass('was-validated');showToast('Please complete the highlighted fields.','error');return}if(form.id==='registerForm'){var p=$('#password').val(),c=$('#confirmPassword').val();if(p!==c){$('#confirmPassword')[0].setCustomValidity('Passwords do not match');$(form).addClass('was-validated');showToast('Passwords do not match.','error');return}else{$('#confirmPassword')[0].setCustomValidity('')}}showToast($(form).data('success')||'Form submitted successfully.','success');form.reset();$(form).removeClass('was-validated');});
$('#confirmPassword,#password').on('input',function(){var c=document.getElementById('confirmPassword');if(c)c.setCustomValidity($('#password').val()&&c.value!==$('#password').val()?'Passwords do not match':'')});
$('.js-ajax-modal').on('click',function(e){e.preventDefault();var url=$(this).data('url'),target=$(this).data('target');var $modal=$(target);$modal.find('.modal-content').html('<div class="p-5 text-center"><div class="spinner-border" role="status"></div><p class="mt-3 mb-0">Loading with Ajax...</p></div>');$modal.modal('show');$.ajax({url:url,method:'GET',dataType:'html'}).done(function(html){$modal.find('.modal-content').html(html)}).fail(function(){$modal.find('.modal-content').html('<div class="modal-header"><h5 class="modal-title">Ajax demo</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><p>The modal file could not be loaded. Run the project using Live Server or GitHub Pages because browsers block Ajax on <code>file://</code>.</p></div>');showToast('Ajax needs Live Server / GitHub Pages.','error')});});
$('.js-filter').on('click',function(){var key=$(this).data('filter');$('.js-filter').removeClass('active');$(this).addClass('active');$('.product-col').each(function(){var match=key==='all'||$(this).data('category')===key;$(this).toggle(match)});});
$('.js-search').on('submit',function(e){e.preventDefault();var q=$(this).find('input').val().trim();if(q){window.location='products.html?q='+encodeURIComponent(q)}});
if($('#productGrid').length){var params=new URLSearchParams(window.location.search),q=(params.get('q')||'').toLowerCase();if(q){$('.product-col').each(function(){var hit=$(this).text().toLowerCase().indexOf(q)!==-1;$(this).toggle(hit)});showToast('Search results for: '+q,'info')}}
if($('#cartList').length){renderCart()}
});
function renderCart(){var cart=getCart(),$list=$('#cartList'),$total=$('#cartTotal');$list.empty();if(!cart.length){$list.html('<div class="empty-state"><i class="fas fa-shopping-bag fa-2x mb-3"></i><h4>Your bag is empty</h4><p class="mb-3">Discover a fragrance and add it to your bag.</p><a class="btn btn-lumina" href="products.html">Shop perfumes</a></div>');$total.text('$0.00');return}var total=0;cart.forEach(function(x,i){total+=x.price*x.qty;$list.append('<div class="card cart-row"><div class="card-body d-flex align-items-center"><img class="cart-thumb mr-3" src="'+x.image+'" alt="'+x.name+'"><div class="flex-grow-1"><h5 class="mb-1">'+x.name+'</h5><div class="text-muted">Qty: '+x.qty+'</div><strong>$'+(x.price*x.qty).toFixed(2)+'</strong></div><button class="btn btn-sm btn-outline-danger js-remove" data-index="'+i+'"><i class="fas fa-trash"></i></button></div></div>')});$total.text('$'+total.toFixed(2));$('.js-remove').on('click',function(){var idx=Number($(this).data('index')),cart=getCart();cart.splice(idx,1);setCart(cart);renderCart();showToast('Item removed from your bag.','info')});}
})(jQuery);
